version: "3.8"

services:
  wyoming-piper:
    build: .
    environment:
      - VOICE=en_US-ryan-low
      # Optional:
      # - USE_CUDA=1
      # - NO_STREAMING=1
      # - SPEAKER=
      # - NOISE_SCALE=
      # - LENGTH_SCALE=
      # - NOISE_W_SCALE=
      # - SAMPLES_PER_CHUNK=
      # - DOWNLOAD_DIR=
    ports:
      - "10200:10200"
    volumes:
      - ./data:/data
    restart: unless-stopped
